// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFbFJ1GeKpvMKkhehTf7r5T1CMHh3eoqg',
    appId: '1:471797074685:web:f57bfb93d5718454bf8c94',
    messagingSenderId: '471797074685',
    projectId: 'ereader-b4b93',
    authDomain: 'ereader-b4b93.firebaseapp.com',
    storageBucket: 'ereader-b4b93.appspot.com',
    measurementId: 'G-0Y2ECR7NX2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTrQAgJbW1KJerW625MFvc7oV17GR4T10',
    appId: '1:471797074685:android:19d505a7473ae18cbf8c94',
    messagingSenderId: '471797074685',
    projectId: 'ereader-b4b93',
    storageBucket: 'ereader-b4b93.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_wfq0oGxVmND4b6iRDeTT58s8bzfDMJY',
    appId: '1:471797074685:ios:e6dc24a32e196674bf8c94',
    messagingSenderId: '471797074685',
    projectId: 'ereader-b4b93',
    storageBucket: 'ereader-b4b93.appspot.com',
    iosClientId: '471797074685-hr4nhj9h95cp066gkj1b4j94sb75uaro.apps.googleusercontent.com',
    iosBundleId: 'com.maxshaberman.ereader',
  );
}
