// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpbJ7uhc1oVSth0GPZRLejclSxZWDQTjY',
    appId: '1:529389859869:web:c5fff6ed503a022a9bc2f4',
    messagingSenderId: '529389859869',
    projectId: 'ereader-341202',
    authDomain: 'ereader-341202.firebaseapp.com',
    storageBucket: 'ereader-341202.appspot.com',
    measurementId: 'G-V1ZZK6S218',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtpILEVVSHOauZc4h2EiDYpGH0NkxgATc',
    appId: '1:529389859869:android:c43fc251048421d79bc2f4',
    messagingSenderId: '529389859869',
    projectId: 'ereader-341202',
    storageBucket: 'ereader-341202.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEaaP4Uq4lJHbGt5daumeG4Xu2UQ4PiRo',
    appId: '1:529389859869:ios:98f9c16b1b4811b09bc2f4',
    messagingSenderId: '529389859869',
    projectId: 'ereader-341202',
    storageBucket: 'ereader-341202.appspot.com',
    iosClientId: '529389859869-8ipfjj6mjqbsnba7pir8r0suci4t524q.apps.googleusercontent.com',
    iosBundleId: 'com.maxshaberman.ereader',
  );
}
